spring.application.name=exam
spring.main.allow-bean-definition-overriding=true

#####################################
# JPA
#####################################
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/oauth2-db
spring.datasource.username=oauth2-db
spring.datasource.password=oauth2-db
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#####################################
# u2ware-stomp
#####################################
# io.u2ware.common.stomp.url=ws://localhost:9030/stomp
# io.u2ware.common.stomp.subscriptions.repairs=/topic/repairs
# io.u2ware.common.stomp.subscriptions.sessions=/topic/sessions

#####################################
# Oauth2
#####################################
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9020/oauth2/jwks

logging.exception-conversion-word=%ex{short}
